name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build-env:
    name: "Build Environment"
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install PHP with extensions
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: '8.2'
        tools: phpunit, phpstan, cs2pr
        coverage: xdebug
      env:
        fail-fast: true

    - name: Setup problem matchers for PHPUnit
      run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies with Composer
      run: composer install --prefer-dist --no-progress

  coding-standards:
    name: "Coding Standards"
    needs: build-env
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore Composer cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install PHP with extensions
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: '8.2'
        tools: phpstan

    - name: Install Composer dependencies (Skip if already restored)
      run: composer install --prefer-dist --no-progress
      if: steps.composer-cache.outputs.cache-hit != 'true'

    - name: Run PHPStan for static analysis
      run: phpstan analyse

  tests:
    name: "Tests"
    needs: build-env
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore Composer cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install PHP with extensions
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: '8.2'
        tools: phpunit
        coverage: xdebug

    - name: Install Composer dependencies (Skip if already restored)
      run: composer install --prefer-dist --no-progress
      if: steps.composer-cache.outputs.cache-hit != 'true'

    - name: Run PHPUnit tests with coverage
      run: phpunit tests --coverage-text
